# ?? API ??
nexon.api.key=test_f0308276b6ff3e284f0e73114427db9f38c6cd223598a036c9b413e9c368b38eefe8d04e6d233bd35cf2fabdeb93fb0d
nexon.api.base.url=https://open.api.nexon.com/maplestory/v1

# ?????? ??
app.name=?????? ??? ??
app.version=1.0.0
app.window.width=600
app.window.height=400

# API ???? ?? (???)
api.connect.timeout=5000
api.read.timeout=10000

# UI ??
ui.theme=modern
ui.animation.enabled=true